### ISSUE TITLE
403 Forbidden!

### ISSUE THREAD

**Issue by dr5hn** [MartinsOnuoha/auto-voice#13]
Hey Martins,

I 💚  all of your innovations out there! 

I see a glitch in this one, can you please fix it?
<img width="833" alt="Screenshot 2022-01-14 at 11 49 52 AM" src="https://user-images.githubusercontent.com/6929121/149461143-a3ca3274-e344-4f77-8702-cd140b7f3a2a.png">

**Comment by MartinsOnuoha** [comment]
Hi @dr5hn, I'm also a fan of your work.
Thanks for pointing this out, The URL is actually incorrect, I have updated it now.
