### ISSUE TITLE
Uncaught (in promise) Error: GraphQL error: field "templates" not found in type: 'query_root'

### ISSUE THREAD

**Issue by mohamed-amine-melliti** [MartinsOnuoha/auto-voice#14]
I've got yhis error please help me :) 
![Capture](https://user-images.githubusercontent.com/48659471/170694978-6859af8e-76a4-4cbb-bb7a-2e63b4429891.JPG)

**Comment by MartinsOnuoha** [comment]
Are you running this locally?

**Comment by mohamed-amine-melliti** [comment]
yes sir , and created graphql endpoint using hasura website

**Comment by mohamed-amine-melliti** [comment]
i think  i data.json to use it to create graphql schema . can you give it to me ?

**Comment by mohamed-amine-melliti** [comment]
please could u help me :(

**Comment by mohamed-amine-melliti** [comment]
i inserted the data manually . Done !

**Comment by MartinsOnuoha** [comment]
Alright.
